#:schema node_modules/wrangler/config-schema.json

# -- Compability
compatibility_date = "2024-07-22"
compatibility_flags = ["nodejs_compat"]

# -- Project configs
account_id = "6b6aeac19e4aad3f30b4e6acb7f10819"
main = "src/entry.ts"
workers_dev = false
minify = true

# -- Smart placement
[placement]
mode = "smart"

# -- Static files
[site]
bucket = "../site/dist"

####################################################################################################

# -- PRODUCTION --

[env.prod]
name = "kesim"

# -- Routes
routes = [
	{pattern="zhiurl.cn", custom_domain=true},
	{pattern="api.zhiurl.cn", custom_domain=true},
]

# -- KV Bindings
kv_namespaces = [
  {binding="KV_LINKS", id="2a46e985924441fb94e4ab3200461cb6"}
]

# -- D1 Bindings
d1_databases = [
  {binding="D1_LINKS", database_name="kesim", database_id="a5ccc301-5279-47a1-8559-0646b1965d95" }
]

# -- Limiter Bindings
[[env.prod.unsafe.bindings]]
name = "API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "2000001" # an number identifier, unique to your account
simple = {limit = 3, period = 10} # [limit, # of access per] [period, 10 or 60 (seconds)]

# -- ENV vars
[env.prod.vars]
ENV = "prod"
DEBUG_MODE = false
CFG_SITE_ORIGIN = "https://zhiurl.cn"
CFG_SITE_HOSTNAME = "zhiurl.cn"
CFG_SITE_API_ORIGIN = "https://api.zhiurl.cn"
CFG_SITE_API_HOSTNAME = "api.zhiurl.cn"
CFG_REDIR_ORIGIN = "https://zhiurl.cn"
CFG_REDIR_HOSTNAME = "zhiurl.cn"
CFG_RANDOM_SLUG_LENGTH = 5
CFG_MIN_SLUG_LENGTH = 3
CFG_MAX_SLUG_LENGTH = 64
CFG_MIN_URL_LENGTH = 10
CFG_MAX_URL_LENGTH = 2048
CFG_DEFAULT_CACHE_AGE = 3600 # an hour
CFG_DEFAULT_STATIC_CACHE_AGE = 86400 # a day
CFG_HASHED_STATIC_CACHE_AGE = 31536000 # a year
CFG_REDIRECT_CACHE_AGE = 31536000 # a year
CF_STATIC_ASSET_TTL = 172800 # 2 days
CF_KV_CACHE_TTL = 86400 # a day
CF_TURNSTILE_ENABLED = true
CF_TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"

####################################################################################################

####################################################################################################

# -- LOCAL --

[env.local]
name = "kesim-local"

# -- KV Bindings
kv_namespaces = [
  {binding="KV_LINKS", id="767fc2258dd94aa09ddcacdac19b1e23"}
]

# -- D1 Bindings
d1_databases = [
  {binding="D1_LINKS", database_name="kesim", database_id="7356670a-5a76-414d-b8e0-92c30ed0f743" }
]

# -- Limiter Bindings
[[env.local.unsafe.bindings]]
name = "API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "2000001" # an number identifier, unique to your account
simple = {limit = 3, period = 10} # [limit, # of access per] [period, 10 or 60 (seconds)]

# -- ENV vars
[env.local.vars]
ENV = "local"
DEBUG_MODE = true
CFG_SITE_ORIGIN = "https://local.kes.im:5000"
CFG_SITE_HOSTNAME = "local.kes.im"
CFG_SITE_API_ORIGIN = "https://api.local.kes.im:3000"
CFG_SITE_API_HOSTNAME = "api.local.kes.im"
CFG_REDIR_ORIGIN = "https://local.kes.im:3000"
CFG_REDIR_HOSTNAME = "local.kes.im"
CFG_RANDOM_SLUG_LENGTH = 5
CFG_MIN_SLUG_LENGTH = 3
CFG_MAX_SLUG_LENGTH = 64
CFG_MIN_URL_LENGTH = 10
CFG_MAX_URL_LENGTH = 2048
CFG_DEFAULT_CACHE_AGE = 0
CFG_DEFAULT_STATIC_CACHE_AGE = 0
CFG_HASHED_STATIC_CACHE_AGE = 0
CFG_REDIRECT_CACHE_AGE = 0
CF_STATIC_ASSET_TTL = 0
CF_KV_CACHE_TTL = 60
CF_TURNSTILE_ENABLED = false
CF_TURNSTILE_VERIFY_URL = ""

####################################################################################################
